version: '3.4'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  myservice:
    build: ./MyService
    environment:
      - DB_CONNECTION_STRING=Host=postgres;Port=5432;Database=mydb;Username=user;Password=password
    ports:
      - "5000:80"
    depends_on:
      - postgres