version: '3.4'

services:
  flyway:
    image: flyway/flyway
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/sql:/flyway/sql
      - ${PWD}/docker-flyway.config:/flyway/conf/flyway.config
    depends_on:
      - postgres
  postgres:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: stifel
      POSTGRES_PASSWORD: passwerd
      POSTGRES_DB: stifel
      ASPNETCORE_ENVIRONMENT: development
    ports:
      - "5432:5432"
  service:
    image: service
    environment:
      - DB_CONNECTION_STRING=Host=postgres;Port=5432;Database=stifel;Username=stifel;Password=passwerd
    ports:
      - "8080:8080"
    depends_on:
      - flyway